### PR TITLE
refactor: mark vue as official

### PR DESCRIPTION
**Pull request by ferferga**
Vue is indeed an official client.

A few more things, but out of the scope of this PR and leaving it up to the maintainers of this curated list:

* Not sure if music/reader distinctions are just for clients that are focused in those specific media types or it's applicable if it's supported. In the case of Vue, although it wants to cover all use cases, I mainly use Jellyfin for listening music, so the music playback it's one of the things that I think it does really good. We have [a cool fullscreen player](https://github.com/jellyfin/jellyfin-vue/pull/520) and a [spectogram](https://github.com/jellyfin/jellyfin-vue/pull/2043).
* We also have builds for Windows/MacOS/Linux using Tauri but it's provided in a best-effort basis and we don't ship it "first and foremost". We have them continuosly built and delivered though [GitHub Actions](https://github.com/jellyfin/jellyfin-vue/actions/workflows/release.yml) (check artifacts for a run and you'll find it). We do the same thing for PRs, all the building pipeline is the same regardless.

### CODE REVIEW

**Comment by darmiel** [comment]
Thank you for your PR!

> Not sure if music/reader distinctions are just for clients that are focused in those specific media types or it's applicable if it's supported.

We are flexible regarding client types, allowing a client to have multiple types as long as it supports them. Therefore, you are welcome to add the music type. The only issue I see is that we currently do not have a dedicated video type. Using the ` 🎵 ` tag might give the impression that Vuefin is an audio-only player. (Maybe we adapt the list in the future to include a separate video tag, which would help better recognize clients that offer both audio and video support.)

> We also have builds for Windows/MacOS/Linux using Tauri [...]

If you offer builds for these systems, we are happy to add the platforms. (Addding download links for the artifacts may be difficult, however.)

**Comment by ferferga** [comment]
@darmiel Added the same link I gave you linking to the release workflow with the GitHub. Probably not what most people will be used, but it can be easily found if investigated a little.

As a side note (and for another PR), why not a different icon for official clients? I'd never link a blue point (see picture in Windows, perhaps in MacOS or other systems is more clear) to something official:

image

Why not a green checkmark for instance? ✅

**Review by darmiel — APPROVED** [review]

**Comment by darmiel** [comment]
We didn't use the green checkmark, because it's already used in the table. But maybe we can use either a different emoji like ✨ or 🛡️, or just go with a blue checkmark image instead of an emoji

**Comment by ferferga** [comment]
@darmiel Definitely yes, would be much clear.

I'll leave it up to you, you're the maintainer so it's your choice! :P

**Pull request merged**
