### PR TITLE
added new banner.png

### PR DESCRIPTION
**Pull request by UdonCodes**
added the new banner.png and placed it into an assets folder

### CODE REVIEW

**Comment by statzie** [comment]
Looks good already 🙂 
However, could you please remove the white "awesome-jellyfin" banner on the right side? 
I think it looks a bit too big an takes too much space.

**Comment by UdonCodes** [comment]
> Looks good already 🙂 However, could you please remove the white "awesome-jellyfin" banner on the right side? I think it looks a bit too big an takes too much space.
> 
> Or make it a little bit smaller (like the current one) and maybe add the GitHub logo back to make it more interesting.

Sure, which one do you prefer ?
AJ-01b
AJ-01a

**Comment by statzie** [comment]
> > Looks good already 🙂 However, could you please remove the white "awesome-jellyfin" banner on the right side? I think it looks a bit too big an takes too much space.
> > Or make it a little bit smaller (like the current one) and maybe add the GitHub logo back to make it more interesting.
> 
> Sure, which one do you prefer ? AJ-01b AJ-01a

Thanks! I think I like the second one a bit more. Wdyt @TomRomeo @darmiel ?

**Comment by TomRomeo** [comment]
I agree, I like the second one more! :)

**Review by darmiel — APPROVED** [review]

**Comment by ReenigneArcher** [comment]
Could I ask, what tool did you use to generate this?

**Comment by UdonCodes** [comment]
@ReenigneArcher I think at that time I was still using Affinity Designer, but it could have been Inkscape as well, since Affinity only runs on Windows and I had to drop my Windows VM around that time.

**Pull request merged**
